from __future__ import annotations

import hashlib
import json
import sqlite3
from pathlib import Path

import pytest

from runtime.research_runner.derived_companion_receipt import (
    COMPANION_OPERATION,
    COMPANION_SEAM_ID,
    SettledCompanionReceiptVerifier,
    companion_operation_digest,
)
from substrate.research_artifact.grounded_companion_answer import AnswerAdmissionExpectation
from substrate.research_spend import (
    BindingConflict,
    CompanionExecutionState,
    IdempotencyConflict,
    InvalidTransition,
    PaidHoldIntent,
    PaidHoldState,
    ResearchSpendLedger,
    RunBinding,
)
from substrate.research_spend.ledger import (
    _DDL,
    _MIGRATIONS,
    APPLICATION_ID,
    SCHEMA_VERSION,
)

TURN_ID = "dturn_" + "1" * 32
PACK_SHA = "2" * 64
PROVIDER_SHA = "3" * 64


def _output(text: str = "Lift is generated by pressure differences.") -> str:
    return json.dumps(
        {
            "claims": [{"citation_ids": ["dchunk_" + "4" * 64], "text": text}],
            "schema_version": "antiek.derived-companion-answer.v1",
        },
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )


def _fixture(tmp_path: Path, *, failure_injector=None, seam: str = COMPANION_SEAM_ID):
    path = tmp_path / "spend.sqlite3"
    ledger = ResearchSpendLedger(path, failure_injector=failure_injector)
    ledger.ensure_schema()
    binding = RunBinding("run-companion-1", "owner-a", "session-a", PACK_SHA, 1)
    ledger.create_or_reopen_run("create-companion-run", binding, 100)
    hold = ledger.reserve_paid(
        "reserve-companion",
        binding,
        PaidHoldIntent(
            reservation_key="companion-reservation",
            seam_id=seam,
            provider="verified-provider",
            model="grounded-model",
            operation=COMPANION_OPERATION,
            operation_digest=companion_operation_digest(TURN_ID, PACK_SHA),
            projection_digest="5" * 64,
            rate_snapshot="verified-provider:2026-07-15",
            provider_idempotency_key="6" * 64,
        ),
        20,
    )
    return path, ledger, binding, hold


def _prepare(ledger, binding, hold):
    return ledger.prepare_companion_execution(
        "prepare-companion", binding, hold.hold_id, TURN_ID, PACK_SHA
    )


def test_prepare_is_durable_owner_private_replayable_and_spend_neutral(tmp_path: Path) -> None:
    path, ledger, binding, hold = _fixture(tmp_path)
    before = ledger.balance(binding.run_id)
    prepared, created = _prepare(ledger, binding, hold)
    replay, replay_created = _prepare(ResearchSpendLedger(path), binding, hold)
    assert created is True and replay_created is False
    assert replay == prepared
    assert prepared.state is CompanionExecutionState.PREPARED
    assert prepared.output_json is None
    assert ledger.balance(binding.run_id) == before
    assert ledger.hold(hold.hold_id).state is PaidHoldState.RESERVED
    with pytest.raises(BindingConflict, match="unavailable"):
        ledger.companion_execution(prepared.execution_id, "owner-b")


def test_prepare_refuses_changed_command_wrong_hold_and_non_reserved_state(tmp_path: Path) -> None:
    _path, ledger, binding, hold = _fixture(tmp_path)
    prepared, _ = _prepare(ledger, binding, hold)
    with pytest.raises(IdempotencyConflict):
        ledger.prepare_companion_execution(
            "prepare-companion",
            binding,
            hold.hold_id,
            "dturn_" + "7" * 32,
            PACK_SHA,
        )
    with pytest.raises(BindingConflict):
        ledger.prepare_companion_execution(
            "prepare-other", binding, "missing-hold", TURN_ID, PACK_SHA
        )
    ledger.mark_dispatch_possible("dispatch", hold.hold_id)
    assert ledger.companion_execution(prepared.execution_id, "owner-a").state is (
        CompanionExecutionState.PREPARED
    )
    other_path, other, other_binding, other_hold = _fixture(tmp_path / "other", seam="wrong.seam")
    del other_path
    with pytest.raises(BindingConflict, match="not bound"):
        _prepare(other, other_binding, other_hold)


def test_completion_atomically_settles_and_reopens_exact_output_and_receipt(tmp_path: Path) -> None:
    path, ledger, binding, hold = _fixture(tmp_path)
    prepared, _ = _prepare(ledger, binding, hold)
    ledger.mark_dispatch_possible("dispatch-companion", hold.hold_id)
    completed = ledger.complete_companion_execution(
        "settle-companion",
        prepared.execution_id,
        "owner-a",
        12,
        _output(),
        PROVIDER_SHA,
    )
    reopened = ResearchSpendLedger(path).companion_execution(prepared.execution_id, "owner-a")
    assert reopened == completed
    assert completed.state is CompanionExecutionState.COMPLETED
    assert completed.output_json == _output()
    assert completed.output_digest == hashlib.sha256(_output().encode()).hexdigest()
    assert ledger.hold(hold.hold_id).state is PaidHoldState.SETTLED
    assert ledger.balance(binding.run_id).held_cents == 0
    receipt = SettledCompanionReceiptVerifier(ledger, "owner-a", hold.hold_id)(
        AnswerAdmissionExpectation(
            turn_id=TURN_ID,
            evidence_pack_sha256=PACK_SHA,
            output_digest=completed.output_digest,
        )
    )
    assert receipt.provider == "verified-provider" and receipt.status == "settled"
    assert (
        ledger.complete_companion_execution(
            "settle-companion",
            prepared.execution_id,
            "owner-a",
            12,
            _output(),
            PROVIDER_SHA,
        )
        == completed
    )


@pytest.mark.parametrize("changed", ["output", "cost", "response", "owner"])
def test_completed_replay_refuses_changed_intent(tmp_path: Path, changed: str) -> None:
    _path, ledger, _binding, hold = _fixture(tmp_path)
    prepared, _ = _prepare(ledger, _binding, hold)
    ledger.mark_dispatch_possible("dispatch", hold.hold_id)
    ledger.complete_companion_execution(
        "settle", prepared.execution_id, "owner-a", 10, _output(), PROVIDER_SHA
    )
    args = {
        "command_key": "settle",
        "execution_id": prepared.execution_id,
        "owner_id": "owner-a",
        "actual_cents": 10,
        "output_json": _output(),
        "provider_response_digest": PROVIDER_SHA,
    }
    if changed == "output":
        args["output_json"] = _output("changed")
    elif changed == "cost":
        args["actual_cents"] = 9
    elif changed == "response":
        args["provider_response_digest"] = "8" * 64
    else:
        args["owner_id"] = "owner-b"
    with pytest.raises((IdempotencyConflict, BindingConflict)):
        ledger.complete_companion_execution(**args)


@pytest.mark.parametrize(
    "stage",
    [
        "settle:after_run_update",
        "settle:after_hold_update",
        "settle:after_command",
        "settle:after_event",
        "complete_companion_execution:after_journal_update",
        "complete_companion_execution:before_commit",
    ],
)
def test_precommit_failure_rolls_back_output_and_settlement(
    tmp_path: Path,
    stage: str,
) -> None:
    armed = False

    def fail(current: str) -> None:
        if armed and current == stage:
            raise RuntimeError("injected completion crash")

    path, ledger, binding, hold = _fixture(tmp_path, failure_injector=fail)
    prepared, _ = _prepare(ledger, binding, hold)
    ledger.mark_dispatch_possible("dispatch", hold.hold_id)
    armed = True
    with pytest.raises(RuntimeError, match="injected"):
        ledger.complete_companion_execution(
            "settle", prepared.execution_id, "owner-a", 10, _output(), PROVIDER_SHA
        )
    reopened = ResearchSpendLedger(path)
    assert (
        reopened.companion_execution(prepared.execution_id, "owner-a").state
        is CompanionExecutionState.PREPARED
    )
    assert reopened.hold(hold.hold_id).state is PaidHoldState.DISPATCH_POSSIBLE
    assert reopened.balance(binding.run_id).held_cents == 20


def test_lost_completion_acknowledgment_reopens_committed_output(tmp_path: Path) -> None:
    armed = False

    def fail(stage: str) -> None:
        if armed and stage == "complete_companion_execution:after_commit":
            raise RuntimeError("acknowledgment lost")

    path, ledger, binding, hold = _fixture(tmp_path, failure_injector=fail)
    prepared, _ = _prepare(ledger, binding, hold)
    ledger.mark_dispatch_possible("dispatch", hold.hold_id)
    armed = True
    with pytest.raises(RuntimeError, match="acknowledgment"):
        ledger.complete_companion_execution(
            "settle", prepared.execution_id, "owner-a", 10, _output(), PROVIDER_SHA
        )
    reopened = ResearchSpendLedger(path)
    assert (
        reopened.companion_execution(prepared.execution_id, "owner-a").state
        is CompanionExecutionState.COMPLETED
    )
    assert reopened.hold(hold.hold_id).state is PaidHoldState.SETTLED


def test_completion_refuses_overspend_invalid_output_and_unmarked_send(tmp_path: Path) -> None:
    _path, ledger, _binding, hold = _fixture(tmp_path)
    prepared, _ = _prepare(ledger, _binding, hold)
    with pytest.raises(InvalidTransition):
        ledger.complete_companion_execution(
            "settle", prepared.execution_id, "owner-a", 10, _output(), PROVIDER_SHA
        )
    ledger.mark_dispatch_possible("dispatch", hold.hold_id)
    with pytest.raises(ValueError, match="canonical"):
        ledger.complete_companion_execution(
            "settle", prepared.execution_id, "owner-a", 10, '{"z": 1}', PROVIDER_SHA
        )
    with pytest.raises(Exception, match="requested"):
        ledger.complete_companion_execution(
            "settle", prepared.execution_id, "owner-a", 21, _output(), PROVIDER_SHA
        )


def test_journal_triggers_reject_rewrite_and_delete(tmp_path: Path) -> None:
    path, ledger, binding, hold = _fixture(tmp_path)
    prepared, _ = _prepare(ledger, binding, hold)
    with sqlite3.connect(path) as connection:
        with pytest.raises(sqlite3.IntegrityError, match="transition rejected"):
            connection.execute("UPDATE research_companion_executions SET owner_id='owner-b'")
        with pytest.raises(sqlite3.IntegrityError, match="durable"):
            connection.execute("DELETE FROM research_companion_executions")
    assert ledger.companion_execution(prepared.execution_id, "owner-a") == prepared


@pytest.mark.parametrize("statement_index", range(1, len(_MIGRATIONS[6]) + 1))
def test_v6_journal_migration_rolls_back_atomically(
    tmp_path: Path,
    statement_index: int,
) -> None:
    path = tmp_path / f"v6-{statement_index}.sqlite3"
    with sqlite3.connect(path) as connection:
        for statement in (
            *_DDL,
            *_MIGRATIONS[2],
            *_MIGRATIONS[3],
            *_MIGRATIONS[4],
            *_MIGRATIONS[5],
        ):
            connection.execute(statement)
        connection.execute(f"PRAGMA application_id={APPLICATION_ID}")
        connection.execute("PRAGMA user_version=6")

    def fail(stage: str) -> None:
        if stage == f"schema:6:after_migration:{statement_index}":
            raise RuntimeError("migration interrupted")

    with pytest.raises(RuntimeError, match="interrupted"):
        ResearchSpendLedger(path, failure_injector=fail).ensure_schema()
    with sqlite3.connect(path) as connection:
        assert connection.execute("PRAGMA user_version").fetchone()[0] == 6
        assert (
            connection.execute(
                "SELECT count(*) FROM sqlite_master "
                "WHERE type='table' AND name='research_companion_executions'"
            ).fetchone()[0]
            == 0
        )
    ResearchSpendLedger(path).ensure_schema()
    with sqlite3.connect(path) as connection:
        assert connection.execute("PRAGMA user_version").fetchone()[0] == SCHEMA_VERSION
