"""Multimedia planning and generation substrate.

SPR-02 starts with the plan-before-render layer; SPR-03 adds the provider router;
SPR-04 adds chaptered audio assembly + a playback read-model;
SPR-05 adds the Ken Burns video documentary assembly (audio is timing truth). Provider adapters
that spend money stay operator-gated; importing this package must not require paid
media credentials (CI runs against the deterministic fake TTS).
"""

from .audio_assembly import (
    AudioExperience,
    ChapterAudio,
    assemble_audio_experience,
)
from .authorized_production_worker import (
    AuthorizedProductionError,
    AuthorizedProductionRequest,
    AuthorizedProductionRuntime,
    AuthorizedProductionUnavailable,
    ChapterNarrationAuthority,
    produce_authorized_multimedia,
)
from .bedrock_live_guard_acquisition import (
    BedrockLiveGuardAcquisitionError,
    CustodyAttestationClient,
    LiveGuardAcquisitionAttempt,
    LiveGuardAcquisitionCommand,
    LiveGuardAcquisitionCoordinator,
    LiveGuardAcquisitionJournal,
    LiveGuardAcquisitionReceipt,
    OrganizationsGuardEvidenceClient,
    RevocationEvidenceClient,
    RevocationEvidenceVerifier,
    RevocationObservation,
    VerifiedRevocationResult,
)
from .bedrock_live_guard_custody import (
    BedrockLiveGuardCustodyError,
    Cycle34AuthorityVerifier,
    IndependentCustodyAttestation,
    IndependentCustodyVerifier,
    LiveGuardCustodyQualifier,
    LiveGuardCustodyReceipt,
    OrganizationGuardSnapshot,
    VerifiedCustodyResult,
)
from .bedrock_live_guard_journal import (
    LiveGuardAttemptStatus,
    LiveGuardJournalConflict,
    LiveGuardJournalError,
    LiveGuardJournalIntegrityReport,
    LiveGuardJournalUnavailable,
    SqliteLiveGuardAcquisitionJournal,
)
from .bedrock_s3_namespace import (
    NAMESPACE_CONTROL_ACTIONS,
    NAMESPACE_MUTATION_ACTIONS,
    BedrockS3NamespaceError,
    BedrockS3NamespaceLeaseQualifier,
    BedrockS3NamespaceLeaseReceipt,
    IndependentNamespaceLease,
    IndependentNamespaceLeaseVerifier,
    S3NamespaceEvidenceClient,
)
from .bedrock_s3_publication import (
    BedrockS3PublicationError,
    BedrockS3PublicationProfile,
    BedrockS3VersionPublicationReceipt,
    BedrockS3VersionPublisher,
    S3PublicationClient,
)
from .bedrock_workload_bound import (
    BedrockBatchModelProfile,
    BedrockBatchRateSnapshot,
    BedrockBatchWorkloadBound,
    materialize_bedrock_batch_workload,
)
from .hardening import (
    GateFinding,
    GateResult,
    GateStatus,
    MultimediaHardeningReport,
    ShipStatus,
    evaluate_multimedia_asset,
)
from .information_asset import (
    MultimediaInformationAsset,
    MultimediaInformationAssetError,
    MultimediaKnowledgeRegistrar,
    MultimediaKnowledgeRegistrationReceipt,
    MultimediaSourceReference,
    project_multimedia_information_asset,
    register_multimedia_information_asset,
)
from .knowledge_finalization import (
    MultimediaKnowledgeFinalizationError,
    MultimediaKnowledgeFinalizationRequest,
    MultimediaKnowledgeFinalizationResponse,
    MultimediaKnowledgeFinalizationStatus,
    MultimediaKnowledgeRecoveryRequest,
    MultimediaTwinDocument,
    finalize_multimedia_knowledge,
    inspect_multimedia_knowledge_finalization,
    read_multimedia_twin_document,
    recover_multimedia_knowledge_finalization,
)
from .knowledge_registration import (
    CanonicalMultimediaKnowledgeRegistrar,
    MultimediaDistillationState,
    MultimediaKnowledgeRegistrationError,
    MultimediaTwinResult,
    authorize_multimedia_distillation_recovery,
    get_multimedia_distillation_state,
    register_multimedia_with_twin,
)
from .local_provider_exclusion import (
    LocalZeroEvidenceConflict,
    LocalZeroEvidenceUnavailable,
    ProviderExecutionExclusion,
    exclude_provider_executions,
)
from .local_zero_cost_evidence import (
    LocalZeroExternalCostEvidenceV1,
    LocalZeroRunAuthorityV1,
    build_local_audio_zero_cost_evidence,
    build_local_video_zero_cost_evidence,
    verify_local_zero_cost_evidence,
)
from .narration import (
    NarrationParagraph,
    normalize_line,
    normalize_script,
)
from .narration_authorization import (
    NarrationAuthorizationError,
    NarrationAuthorizationRequest,
    NarrationAuthorizationResult,
    TrustedNarrationTerms,
    authorize_multimedia_chapter_narration,
)
from .planner import (
    ChapterPlan,
    CoverageSuggestion,
    EvidenceChunk,
    MultimediaPlan,
    MultimediaPlanRequest,
    StoryboardScene,
    build_multimedia_plan,
)
from .playback import (
    PlaybackChapter,
    PlaybackReadModel,
    RegenerationTarget,
    SourceCard,
    build_playback_read_model,
)
from .production_cost_closure import (
    ProductionByteConstituentV1,
    ProductionByteProjectionV1,
    ProductionCostClosure,
    build_production_byte_cost_closure,
    verify_production_byte_projection,
)
from .production_registration import (
    MultimediaProductionRegistrationError,
    MultimediaProductionRegistrationRequest,
    register_multimedia_production,
)
from .provider_router import (
    BudgetExceeded,
    KreaProviderAdapter,
    MediaGenerationRequest,
    ProviderExecutionRecord,
    ProviderRoute,
    ProviderUnavailable,
    route_media_request,
)
from .read_model import (
    CreateMultimediaDraftRequest,
    MultimediaAssetList,
    MultimediaAssetRecord,
    MultimediaAssetStore,
    MultimediaAssetSummary,
    MultimediaKnowledgeLink,
    SteeringRequest,
)
from .reviewed_visual_registry import (
    RegisterReviewedVisualsRequest,
    ResolvedReviewedVisualSet,
    ReviewedVisualRegistry,
    ReviewedVisualRegistryError,
    ReviewedVisualSetReceipt,
    VisualCandidateBinding,
    get_reviewed_visuals,
    register_reviewed_visuals,
)
from .ship_cost_snapshot import (
    MultimediaShipCostEvidenceConflict,
    MultimediaShipCostEvidenceUnavailable,
    MultimediaShipCostExecutionV1,
    MultimediaShipCostSnapshotV1,
    build_multimedia_ship_cost_snapshot,
    validate_settled_execution,
    verify_multimedia_ship_cost_snapshot,
)
from .steering import (
    RevisionPlan,
    SegmentReuse,
    SteeringIntent,
    SteeringOperation,
    SteeringTranscript,
    build_revision_asset,
    parse_steering_prompt,
    plan_revision,
)
from .tts import (
    FakeTTSProvider,
    TTSProvider,
    TTSRequest,
    TTSResult,
    make_tts_provider,
)
from .verified_playback import (
    MediaByteRange,
    PlaybackMediaMetadata,
    VerifiedPlaybackError,
    VerifiedPlaybackRuntime,
)
from .video import (
    CaptionCue,
    MotionPreset,
    TimelineEntry,
    VideoDocumentaryAsset,
    VideoRenderManifest,
    VideoScene,
    VisualGenerationPlan,
    VisualLabel,
    assemble_video_documentary,
    build_video_scenes,
    captions_from_timeline,
    compile_ken_burns_timeline,
    plan_visual_generation,
    simulate_documentary_render,
)

__all__ = [
    "BedrockLiveGuardAcquisitionError",
    "CustodyAttestationClient",
    "LiveGuardAcquisitionAttempt",
    "LiveGuardAcquisitionCommand",
    "LiveGuardAcquisitionCoordinator",
    "LiveGuardAcquisitionJournal",
    "LiveGuardAcquisitionReceipt",
    "OrganizationsGuardEvidenceClient",
    "RevocationEvidenceClient",
    "RevocationEvidenceVerifier",
    "RevocationObservation",
    "VerifiedRevocationResult",
    "LiveGuardAttemptStatus",
    "LiveGuardJournalConflict",
    "LiveGuardJournalError",
    "LiveGuardJournalIntegrityReport",
    "LiveGuardJournalUnavailable",
    "SqliteLiveGuardAcquisitionJournal",
    "BedrockLiveGuardCustodyError",
    "Cycle34AuthorityVerifier",
    "IndependentCustodyAttestation",
    "IndependentCustodyVerifier",
    "LiveGuardCustodyQualifier",
    "LiveGuardCustodyReceipt",
    "OrganizationGuardSnapshot",
    "VerifiedCustodyResult",
    "NAMESPACE_CONTROL_ACTIONS",
    "NAMESPACE_MUTATION_ACTIONS",
    "BedrockS3NamespaceError",
    "BedrockS3NamespaceLeaseQualifier",
    "BedrockS3NamespaceLeaseReceipt",
    "BedrockS3PublicationError",
    "BedrockS3PublicationProfile",
    "BedrockS3VersionPublicationReceipt",
    "BedrockS3VersionPublisher",
    "IndependentNamespaceLease",
    "IndependentNamespaceLeaseVerifier",
    "S3NamespaceEvidenceClient",
    "S3PublicationClient",
    # Cycle 32 Bedrock workload authority
    "BedrockBatchModelProfile",
    "BedrockBatchRateSnapshot",
    "BedrockBatchWorkloadBound",
    "materialize_bedrock_batch_workload",
    # SPR-02 planner
    "ChapterPlan",
    "CoverageSuggestion",
    "EvidenceChunk",
    "MultimediaPlan",
    "MultimediaPlanRequest",
    "StoryboardScene",
    "build_multimedia_plan",
    # SPR-03 provider router
    "BudgetExceeded",
    "KreaProviderAdapter",
    "MediaGenerationRequest",
    "ProviderExecutionRecord",
    "ProviderRoute",
    "ProviderUnavailable",
    "route_media_request",
    # SPR-04 narration + TTS + assembly + playback
    "NarrationParagraph",
    "normalize_line",
    "normalize_script",
    "FakeTTSProvider",
    "TTSProvider",
    "TTSRequest",
    "TTSResult",
    "make_tts_provider",
    "AudioExperience",
    "ChapterAudio",
    "assemble_audio_experience",
    "PlaybackChapter",
    "PlaybackReadModel",
    "RegenerationTarget",
    "SourceCard",
    "build_playback_read_model",
    # SPR-05 video documentary
    "CaptionCue",
    "MotionPreset",
    "TimelineEntry",
    "VideoDocumentaryAsset",
    "VideoRenderManifest",
    "VideoScene",
    "VisualGenerationPlan",
    "VisualLabel",
    "assemble_video_documentary",
    "build_video_scenes",
    "captions_from_timeline",
    "compile_ken_burns_timeline",
    "plan_visual_generation",
    "simulate_documentary_render",
    # SPR-07 steering + revisions
    "RevisionPlan",
    "SegmentReuse",
    "SteeringIntent",
    "SteeringOperation",
    "SteeringTranscript",
    "build_revision_asset",
    "parse_steering_prompt",
    "plan_revision",
    # SPR-08 evaluation + hardening
    "GateFinding",
    "GateResult",
    "GateStatus",
    "MultimediaHardeningReport",
    "ShipStatus",
    "evaluate_multimedia_asset",
    "MultimediaShipCostEvidenceConflict",
    "MultimediaShipCostEvidenceUnavailable",
    "MultimediaShipCostExecutionV1",
    "MultimediaShipCostSnapshotV1",
    "build_multimedia_ship_cost_snapshot",
    "validate_settled_execution",
    "verify_multimedia_ship_cost_snapshot",
    # MSR-02 production-byte cost closure
    "ProductionByteConstituentV1",
    "ProductionByteProjectionV1",
    "ProductionCostClosure",
    "build_production_byte_cost_closure",
    "verify_production_byte_projection",
    # MSR-03 local zero external provider cost authority
    "LocalZeroEvidenceConflict",
    "LocalZeroEvidenceUnavailable",
    "LocalZeroExternalCostEvidenceV1",
    "LocalZeroRunAuthorityV1",
    "ProviderExecutionExclusion",
    "build_local_audio_zero_cost_evidence",
    "build_local_video_zero_cost_evidence",
    "exclude_provider_executions",
    "verify_local_zero_cost_evidence",
    # HTML knowledge-asset projection
    "MultimediaInformationAsset",
    "MultimediaInformationAssetError",
    "MultimediaKnowledgeRegistrar",
    "MultimediaKnowledgeRegistrationReceipt",
    "MultimediaSourceReference",
    "project_multimedia_information_asset",
    "register_multimedia_information_asset",
    "CanonicalMultimediaKnowledgeRegistrar",
    "MultimediaKnowledgeRegistrationError",
    "MultimediaTwinResult",
    "register_multimedia_with_twin",
    "MultimediaKnowledgeFinalizationError",
    "MultimediaKnowledgeFinalizationRequest",
    "MultimediaKnowledgeFinalizationResponse",
    "MultimediaKnowledgeFinalizationStatus",
    "MultimediaKnowledgeRecoveryRequest",
    "MultimediaTwinDocument",
    "finalize_multimedia_knowledge",
    "inspect_multimedia_knowledge_finalization",
    "recover_multimedia_knowledge_finalization",
    "read_multimedia_twin_document",
    "MultimediaDistillationState",
    "authorize_multimedia_distillation_recovery",
    "get_multimedia_distillation_state",
    # SPR-09 API persistence/read-model
    "CreateMultimediaDraftRequest",
    "MultimediaAssetList",
    "MultimediaAssetRecord",
    "MultimediaAssetStore",
    "MultimediaAssetSummary",
    "MultimediaKnowledgeLink",
    "SteeringRequest",
    # Receipt-verified browser delivery
    "MediaByteRange",
    "PlaybackMediaMetadata",
    "VerifiedPlaybackError",
    "VerifiedPlaybackRuntime",
    "MultimediaProductionRegistrationError",
    "MultimediaProductionRegistrationRequest",
    "register_multimedia_production",
    "NarrationAuthorizationError",
    "NarrationAuthorizationRequest",
    "NarrationAuthorizationResult",
    "TrustedNarrationTerms",
    "authorize_multimedia_chapter_narration",
    "RegisterReviewedVisualsRequest",
    "ResolvedReviewedVisualSet",
    "ReviewedVisualRegistry",
    "ReviewedVisualRegistryError",
    "ReviewedVisualSetReceipt",
    "VisualCandidateBinding",
    "get_reviewed_visuals",
    "register_reviewed_visuals",
    "AuthorizedProductionError",
    "AuthorizedProductionRequest",
    "AuthorizedProductionRuntime",
    "AuthorizedProductionUnavailable",
    "ChapterNarrationAuthority",
    "produce_authorized_multimedia",
]
