import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { createInMemoryTabTreeAdapter } from "./tabTree";
import { setTabOwner, suspendTabDispatch } from "./tabTreeOwner";
import { useTabTrees } from "./tabTreeStore";
import { TabPersistenceStatus } from "./TabPersistenceStatus";
const tabs = () => useTabTrees.getState();
beforeEach(() => { setTabOwner(null); setTabOwner("owner"); tabs().resetTabTrees(); });
afterEach(() => { cleanup(); setTabOwner(null); tabs().resetTabTrees(); vi.restoreAllMocks(); });
it("shows session lifetime and gives a working retry for failed server writes", async () => {
  vi.spyOn(console, "error").mockImplementation(() => {});
  render(<TabPersistenceStatus mothership="reading" />);
  expect(screen.getByRole("status").textContent).toBe("Tabs last for this session.");
  const adapter = createInMemoryTabTreeAdapter(); const save = adapter.save;
  vi.spyOn(adapter, "save").mockRejectedValueOnce(new Error("offline"));
  await act(async () => { await tabs().bindActiveProject(async () => "project", () => adapter); await tabs().ensureMothership("reading"); });
  act(() => { tabs().spawnTab("reading", null, { tab_id: "newTab", kind: "reader", ref: "doc", mothership: "reading" }); });
  expect(screen.getByRole("status").textContent).toBe("Tab changes pending.");
  const retry = await screen.findByRole("button", { name: "Retry saving tabs" });
  expect(screen.getByRole("status").textContent).toBe("Tab changes aren't saved yet.");
  vi.mocked(adapter.save).mockImplementation(save); fireEvent.click(retry);
  await screen.findByText("Tabs saved.");
  expect((await adapter.load("project", "reading")).tree.nodes.newTab).toBeTruthy();
});

it("never displays saved during resumed GET and exposes a working load retry", async () => {
  const adapter = createInMemoryTabTreeAdapter();
  await tabs().bindActiveProject(async () => "project", () => adapter);
  await tabs().ensureMothership("reading");
  render(<TabPersistenceStatus mothership="reading" />);
  expect(screen.getByRole("status").textContent).toBe("Tabs saved.");
  let release: (value: Awaited<ReturnType<typeof adapter.load>>) => void = () => {};
  const gate = new Promise<Awaited<ReturnType<typeof adapter.load>>>((done) => { release = done; });
  const snapshot = await adapter.load("project", "reading");
  const load = adapter.load;
  vi.spyOn(adapter, "load").mockReturnValueOnce(gate);
  act(() => { suspendTabDispatch(); });
  expect(screen.getByRole("status").textContent).toBe("Tab saving is paused.");
  act(() => { setTabOwner("owner"); });
  let loading: Promise<void> = Promise.resolve();
  act(() => { loading = tabs().ensureMothership("reading"); });
  expect(screen.getByRole("status").textContent).toBe("Loading saved tabs.");
  await act(async () => { release(snapshot); await loading; });
  expect(screen.getByRole("status").textContent).toBe("Tabs saved.");
  act(() => { suspendTabDispatch(); });
  vi.mocked(adapter.load).mockRejectedValueOnce(new Error("offline"));
  await act(async () => { setTabOwner("owner"); await tabs().ensureMothership("reading"); });
  expect(screen.getByRole("status").textContent).toBe("Saved tabs are unavailable.");
  vi.mocked(adapter.load).mockImplementation(load);
  fireEvent.click(screen.getByRole("button", { name: "Retry loading tabs" }));
  await screen.findByText("Tabs saved.");
});
