"""HarnessFork — scaffold a per-project extension package."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path


_EXTENSION_PY_TEMPLATE = '''"""Antiek harness fork: {name}

Generated by `antiek harness fork {name}`.
"""

from substrate.hooks import HookRegistry


def register(registry: HookRegistry) -> None:
    """Register this fork's hooks against the substrate registry."""
    return None
'''


_CONFIG_TOML_TEMPLATE = """# Antiek harness fork: {name}

[fork]
name = "{name}"
version = "0.1.0"

[compaction]
# policy = "lossy"
# threshold_pct = 0.85
# keep_first_n = 4
# keep_last_n = 8

[queues]
# autoresearch_fanout = {{ capacity = 20, watermark_pct = 0.8 }}
"""


_README_TEMPLATE = """# Harness fork: {name}

Generated by `antiek harness fork {name}`.

## Apply

```bash
antiek harness apply --fork {name}
```

## Disable temporarily

```bash
touch antiek_extensions/{name}/.disabled
```
"""

_HOOKS_INIT = '"""Hook implementations for this fork."""\n'
_TOOLS_INIT = '"""Additional substrate tools for this fork."""\n'
_PROMPTS_INIT = '"""System-prompt fragments for this fork."""\n'

_SUBDIRS = ("hooks", "tools", "prompts", "adapters")


class ForkAlreadyExists(FileExistsError):
    pass


@dataclass(frozen=True)
class HarnessFork:
    name: str
    path: Path
    has_extension: bool
    has_config: bool

    @classmethod
    def from_path(cls, path: Path) -> "HarnessFork":
        return cls(
            name=path.name,
            path=path,
            has_extension=(path / "extension.py").is_file(),
            has_config=(path / "config.toml").is_file(),
        )


def create_fork(name: str, project_root: Path) -> HarnessFork:
    if not name or "/" in name or ".." in name or name.startswith("."):
        raise ValueError(
            f"fork name must be non-empty, contain no '/' or '..', and not "
            f"start with '.'; got {name!r}"
        )
    ext_root = project_root / "antiek_extensions"
    final_dir = ext_root / name
    if final_dir.exists():
        raise ForkAlreadyExists(f"fork already exists at {final_dir}")

    tmp_dir = ext_root / f".tmp-{name}"
    if tmp_dir.exists():
        shutil.rmtree(tmp_dir)
    tmp_dir.mkdir(parents=True)

    try:
        for sub in _SUBDIRS:
            sd = tmp_dir / sub
            sd.mkdir()
            if sub == "hooks":
                (sd / "__init__.py").write_text(_HOOKS_INIT)
            elif sub == "tools":
                (sd / "__init__.py").write_text(_TOOLS_INIT)
            elif sub == "prompts":
                (sd / "__init__.py").write_text(_PROMPTS_INIT)

        (tmp_dir / "extension.py").write_text(_EXTENSION_PY_TEMPLATE.format(name=name))
        (tmp_dir / "config.toml").write_text(_CONFIG_TOML_TEMPLATE.format(name=name))
        (tmp_dir / "README.md").write_text(_README_TEMPLATE.format(name=name))
        tmp_dir.rename(final_dir)
    except Exception:
        if tmp_dir.exists():
            shutil.rmtree(tmp_dir, ignore_errors=True)
        raise

    return HarnessFork.from_path(final_dir)


def list_forks(project_root: Path) -> list[HarnessFork]:
    ext_root = project_root / "antiek_extensions"
    if not ext_root.is_dir():
        return []
    return [
        HarnessFork.from_path(p)
        for p in sorted(ext_root.iterdir())
        if p.is_dir() and not p.name.startswith(".tmp-")
    ]
