"""Typed event log — the on-policy RL trajectory substrate.

See ``events.py`` for emit/seal/query operations.
Payload schemas (the discriminated union) live in ``substrate/schemas/events.py``;
this package re-exports ``ActionType`` and ``Event`` for back-compat with
callers that import directly from ``substrate.event_log``.
"""

# Keep ANTIEK_PARAM_VERSION importable here too — many call sites read it
# alongside ActionType.
from ..constants import ANTIEK_PARAM_VERSION  # noqa: E402
from ..schemas.events import (  # re-exported from the canonical schema source
    DEFAULT_POLICY_ID,
    EVENT_SCHEMA_VERSION,
    ActionType,
    Event,
)
from .events import (
    EventAppendBatch,
    EventEmitter,
    IdempotencyConflict,
    InvestigationExecutionBusy,
    InvestigationExecutionInvalid,
    InvestigationExecutionSnapshot,
    ResearchBudgetExceeded,
    ResearchBudgetLedgerInvalid,
    ResearchBudgetSnapshot,
    ResearchDelegationSnapshot,
    accept_research_delegation_authorized,
    action_counts,
    append_event_once,
    append_event_once_authorized,
    append_idempotent_typed_event_authorized,
    assert_investigation_execution_authorized,
    claim_investigation_execution_authorized,
    complete_investigation_execution_authorized,
    current_investigation_authority,
    current_investigation_execution,
    default_events_dir,
    emit_typed,
    emit_typed_authorized,
    emit_typed_authorized_strict,
    emit_worker_identity,
    event_append_batch,
    investigation_authority_context,
    investigation_execution_context,
    investigation_execution_mutation,
    locked_trajectory_authorized,
    log_event,
    log_event_authorized,
    mark_research_delegation_issued_authorized,
    prepare_typed_event,
    query_worker_identity,
    release_research_call_authorized,
    release_research_delegation_authorized,
    renew_investigation_execution_authorized,
    require_event_persistence,
    research_call_dispatch_event_id,
    research_delegation_snapshot_authorized,
    reserve_research_call_authorized,
    reserve_research_delegation_authorized,
    seal_investigation,
    seal_investigation_authorized,
    settle_research_call_authorized,
    settle_research_delegation_authorized,
    trajectory,
    trajectory_authorized,
    trajectory_authorized_append_order,
    trajectory_contextual,
    validate_trajectory,
)

__all__ = [
    "ANTIEK_PARAM_VERSION",
    "EVENT_SCHEMA_VERSION",
    "DEFAULT_POLICY_ID",
    "ActionType",
    "Event",
    "EventEmitter",
    "EventAppendBatch",
    "action_counts",
    "append_event_once",
    "append_event_once_authorized",
    "append_idempotent_typed_event_authorized",
    "IdempotencyConflict",
    "InvestigationExecutionBusy",
    "InvestigationExecutionInvalid",
    "InvestigationExecutionSnapshot",
    "ResearchBudgetExceeded",
    "ResearchBudgetLedgerInvalid",
    "ResearchBudgetSnapshot",
    "ResearchDelegationSnapshot",
    "accept_research_delegation_authorized",
    "assert_investigation_execution_authorized",
    "claim_investigation_execution_authorized",
    "complete_investigation_execution_authorized",
    "current_investigation_execution",
    "current_investigation_authority",
    "event_append_batch",
    "investigation_authority_context",
    "investigation_execution_context",
    "investigation_execution_mutation",
    "default_events_dir",
    "emit_typed",
    "emit_typed_authorized",
    "emit_typed_authorized_strict",
    "emit_worker_identity",
    "log_event",
    "log_event_authorized",
    "locked_trajectory_authorized",
    "prepare_typed_event",
    "query_worker_identity",
    "renew_investigation_execution_authorized",
    "release_research_call_authorized",
    "release_research_delegation_authorized",
    "research_delegation_snapshot_authorized",
    "research_call_dispatch_event_id",
    "require_event_persistence",
    "reserve_research_call_authorized",
    "reserve_research_delegation_authorized",
    "seal_investigation",
    "seal_investigation_authorized",
    "settle_research_call_authorized",
    "settle_research_delegation_authorized",
    "mark_research_delegation_issued_authorized",
    "trajectory",
    "trajectory_authorized",
    "trajectory_authorized_append_order",
    "trajectory_contextual",
    "validate_trajectory",
]
