"""Midnight Oil — autonomous research sub-agent swarm (offline-from-UI).

Product surface: operator sets goals + work duration; system recommends a
price ceiling; after **explicit approve** a worker iterates without a
workstation session. Spend hard-halts at the approved ceiling and deposits
partial HTML + twin notes via ``substrate.engagement_spine``.

No network is required for the pure job/ceiling/approve/worker/deposit path —
tests inject clocks and spawn functions.
"""

from __future__ import annotations

from .ceiling import recommend_price_ceiling
from .contracts import (
    ADAPTER_KEYS,
    GateReceipt,
    MidnightOilAppliedRunReceipt,
    MidnightOilApprovalReceipt,
    MidnightOilArtifactContract,
    MidnightOilLaunchPacket,
    MidnightOilPreflight,
    MidnightOilRequest,
    MidnightOilRolePlan,
    MidnightOilRunnerHandoff,
    is_known_adapter_key,
    preflight_midnight_oil,
    validate_receipt_chain,
)
from .deposit import DepositResult, deposit_job_results
from .job import (
    JobStatus,
    MidnightOilJob,
    MidnightOilStepEvidence,
    approve_job,
    create_job,
    get_job,
)
from .live import (
    LiveExecutionFailed,
    LiveExecutionOutcome,
    LiveExecutionPlan,
    LiveOperatorCorpusStep,
    LivePolicyUnsupported,
    RouterIdempotentDispatch,
    build_router_live_plan,
    consume_authorized_live_operation,
    resume_terminal_deposit,
    run_authorized_live_iteration,
)
from .operation_queue import provider_idempotency_key
from .product_path import (
    ANTIEK_MIDNIGHT_OIL_LIVE_STEP_ENV,
    MidnightOilProductResult,
    approve_price_ceiling,
    clear_midnight_oil_live_step,
    configure_midnight_oil_live_step,
    create_recommend_and_approve,
    create_with_recommended_ceiling,
    job_summary_html,
    live_step_enabled,
    live_step_fn_installed,
    live_step_status_payload,
    offline_goal_project_fn,
    offline_goal_step_fn,
    product_result_html,
    resolve_worker_step_fn,
    run_job_offline,
)
from .runner import (
    MidnightOilExecutionReceipt,
    MidnightOilExecutionRequest,
    MidnightOilRoleOutput,
    execute_midnight_oil,
)
from .seams import (
    ALL_SEAMS,
    ArtifactHandle,
    Balance,
    BudgetReservationProvider,
    ControlLedgerAuditRollback,
    FinalHtmlArtifactWriter,
    GraphMutationWriter,
    LedgerEvent,
    MidnightOilSeams,
    ModelProviderRouteExecutor,
    NotAuthorized,
    OperatorLiveDispatchEnablement,
    OperatorSpendGrant,
    OperatorSpendNotAuthorized,
    ReservedBalance,
    RetrievalExecutorSourceReceipts,
    RetrievalResult,
    RollbackReceipt,
    SeamOrderingViolation,
    SourceReceipt,
)
from .worker import (
    ProjectFn,
    StepFn,
    WorkerLease,
    WorkerStepResult,
    lease_authorized_operation,
    run_leased_worker_iteration,
    run_worker_iteration,
    run_worker_loop,
)

__all__ = [
    "ANTIEK_MIDNIGHT_OIL_LIVE_STEP_ENV",
    "DepositResult",
    "ADAPTER_KEYS",
    "ALL_SEAMS",
    "ArtifactHandle",
    "Balance",
    "BudgetReservationProvider",
    "ControlLedgerAuditRollback",
    "GateReceipt",
    "FinalHtmlArtifactWriter",
    "GraphMutationWriter",
    "LedgerEvent",
    "JobStatus",
    "MidnightOilJob",
    "MidnightOilStepEvidence",
    "MidnightOilSeams",
    "MidnightOilProductResult",
    "LiveOperatorCorpusStep",
    "LiveExecutionPlan",
    "LiveExecutionFailed",
    "LiveExecutionOutcome",
    "LivePolicyUnsupported",
    "RouterIdempotentDispatch",
    "MidnightOilExecutionReceipt",
    "MidnightOilExecutionRequest",
    "MidnightOilRoleOutput",
    "ModelProviderRouteExecutor",
    "NotAuthorized",
    "OperatorLiveDispatchEnablement",
    "OperatorSpendGrant",
    "OperatorSpendNotAuthorized",
    "MidnightOilAppliedRunReceipt",
    "MidnightOilApprovalReceipt",
    "MidnightOilArtifactContract",
    "MidnightOilLaunchPacket",
    "MidnightOilPreflight",
    "MidnightOilRequest",
    "MidnightOilRolePlan",
    "MidnightOilRunnerHandoff",
    "ProjectFn",
    "ReservedBalance",
    "RetrievalExecutorSourceReceipts",
    "RetrievalResult",
    "RollbackReceipt",
    "SeamOrderingViolation",
    "SourceReceipt",
    "StepFn",
    "WorkerStepResult",
    "WorkerLease",
    "approve_job",
    "build_router_live_plan",
    "approve_price_ceiling",
    "clear_midnight_oil_live_step",
    "configure_midnight_oil_live_step",
    "consume_authorized_live_operation",
    "create_job",
    "create_recommend_and_approve",
    "create_with_recommended_ceiling",
    "deposit_job_results",
    "get_job",
    "execute_midnight_oil",
    "job_summary_html",
    "is_known_adapter_key",
    "live_step_enabled",
    "live_step_fn_installed",
    "live_step_status_payload",
    "lease_authorized_operation",
    "run_leased_worker_iteration",
    "product_result_html",
    "provider_idempotency_key",
    "preflight_midnight_oil",
    "offline_goal_project_fn",
    "offline_goal_step_fn",
    "recommend_price_ceiling",
    "resolve_worker_step_fn",
    "resume_terminal_deposit",
    "run_job_offline",
    "run_authorized_live_iteration",
    "run_worker_iteration",
    "run_worker_loop",
    "validate_receipt_chain",
]
