import type { CSSProperties } from "react";

import "./werner/animated/animations.css";
import type { WernerMood } from "../design/tokens";
import type { SceneMood } from "../scene/mood";
import { wernerMoodForScene } from "./wernerSceneMap";

// SPR-12 M4 — the idle pose now points at the alpha-cut variant. The
// original `_corrected` raster baked a near-white (≈255,253,253) opaque
// background into every corner pixel (reproduced before the fix:
// Image.getpixel((0,0)) == (255,253,253,255), zero transparent pixels),
// which rendered as an ugly white box behind the top-left rail logo and
// in any blank/empty surface. The transparent variant FLOOD-FILLS the baked
// background inward from the image edges (the flood traverses only neutral
// near-white pixels and is halted by the penguin's closed black outline), so
// only the true surround goes transparent — the white belly/face, never
// reached by the flood, stay FULLY OPAQUE. That is what makes it blend on the
// sun-yellow rail button (light) AND not ghost to muddy grey on dark surfaces
// (the 64px mascot + 72px home hero render straight onto dark). A global
// luminance threshold could not tell belly from background; the flood-fill is
// topological. Generated by tools/brand/cut_werner_bg.py from the same source
// PNG; the source is kept on disk for provenance.
import wernerIdle from "./werner/poses/anchor/werner_default_v5_transparent.png";
// Session-refined thinking + celebrate poses (Imagine, 2026-07-12) — flood-cut
// transparent PNGs under poses/session/. These ARE the product chrome for the
// thinking/celebrate moods (rail AI-working + celebration surfaces consume
// them via this POSE map). Provenance: sessionAssets.ts + brand integrity tests.
// Empty (lost) remains the alpha-cut pose from cut_pose_bg.py.
import wernerThinking from "./werner/poses/session/werner_thinking_session_v1.png";
import wernerEmpty from "./werner/poses/werner_lost_v1_transparent.png";
import wernerCelebrate from "./werner/poses/session/werner_celebrate_session_v1.png";

/**
 * Canonical Werner — the single source of truth for the penguin mark.
 *
 * One component. Four moods only. The art is the operator's Krea-generated
 * penguin (brand-sun-yellow-locked `_corrected` PNGs), the same cute penguin
 * the Login page renders — not the prior hand-built SVG geometry, which never
 * read as cute at any size.
 *
 * The rail calls it cute at 28 px; the hero/celebrate surfaces see it at
 * 64–120 px. Motion is CSS only (the idle sway) and collapses under
 * prefers-reduced-motion via werner/animated/animations.css.
 *
 * Restraint is load-bearing: Werner appears in rail (idle), AI working
 * (thinking), blank states (empty), and core-action complete (celebrate).
 * Nowhere else. See brand/README.md.
 *
 * The static MOODS list and the dev-only runtime guard below are the
 * mechanical enforcement of the four-slot rule. Adding a fifth mood string
 * will throw in development before any visual regression or Storybook render
 * can hide it.
 */

const MOODS = ["idle", "thinking", "empty", "celebrate"] as const;

// Mood → Krea pose. Idle is the cute default/idle (the Login penguin);
// thinking, empty (lost), and celebrate (caught a fish) carry the same
// character into the three other sanctioned slots.
const POSE: Record<(typeof MOODS)[number], string> = {
  idle: wernerIdle,
  thinking: wernerThinking,
  empty: wernerEmpty,
  celebrate: wernerCelebrate,
};

type Props = {
  mood?: WernerMood;
  scene?: SceneMood;
  size?: number;
  label?: string;
  className?: string;
  // Positioning passthrough — animated wrappers (e.g. the toboggan spinner)
  // place the mark absolutely; merged after the intrinsic size box.
  style?: CSSProperties;
};

export default function Werner({
  mood,
  scene,
  size = 28,
  label,
  className,
  style,
}: Props) {
  const effectiveMood = mood ?? (scene ? wernerMoodForScene(scene) : "idle");

  // Dev runtime guard — throws immediately on any string outside the four.
  // This is the mechanical half of U-02; the visual half lives in the rail
  // 28 px render and the CanonicalMoods story. A fifth mood cannot reach
  // production or even a Storybook build without this firing first.
  if (
    process.env.NODE_ENV !== "production" &&
    effectiveMood &&
    !(MOODS as readonly string[]).includes(effectiveMood)
  ) {
    throw new Error(
      `Werner: invalid mood "${effectiveMood}". Only ${MOODS.join(", ")} are permitted. ` +
        "The four-slot restraint is non-negotiable per brand/README.md and U-02.",
    );
  }

  const resolvedMood = effectiveMood as (typeof MOODS)[number];
  // Idle keeps the restrained breathing sway; the keyframe + its
  // prefers-reduced-motion collapse both live in animations.css.
  const rootClass =
    resolvedMood === "idle"
      ? "werner-idle"
      : resolvedMood === "empty"
        ? "werner-pose--empty"
        : "";
  const viewportClass =
    resolvedMood === "empty" ? " werner-pose-viewport--empty" : "";
  const wrapperClass = `${className ? `inline-block align-middle ${className}` : "inline-block align-middle"}${viewportClass}`;

  return (
    <span
      role="img"
      aria-label={label || `Werner ${resolvedMood}`}
      className={wrapperClass}
      style={{ width: size, height: size, ...style }}
    >
      <img
        src={POSE[resolvedMood]}
        alt=""
        aria-hidden="true"
        width={size}
        height={size}
        // The empty raster's authored subject is only 1.4% of its square canvas;
        // its mood-specific class corrects that source framing inside this box.
        className={rootClass}
        style={{
          display: "block",
          width: size,
          height: size,
          objectFit: "contain",
        }}
        draggable={false}
      />
    </span>
  );
}

export type { WernerMood };
