"""Antiek Deep Research Bridge — substrate."""

from __future__ import annotations

from .db_path import (
    default_db_path,
    ensure_research_bridge_initialized,
)
from .dogfood_log import (
    DogfoodLogValidation,
    DogfoodScaffoldResult,
    Wave4Candidate,
    Wave4CandidatesValidation,
    default_dogfood_dir,
    validate_dogfood_log,
    validate_wave4_candidates,
    write_dogfood_scaffold,
)
from .dogfood_report import (
    DogfoodMetrics,
    SessionBlockMetrics,
    SessionDraftExportMetrics,
    SessionSignalMetrics,
    build_dogfood_metrics,
    default_dogfood_metrics_path,
    render_dogfood_report,
)
from .dogfood_verdict import (
    DogfoodVerdictScaffoldResult,
    DogfoodVerdictValidation,
    default_verdict_path,
    validate_verdict_doc,
    write_verdict_scaffold,
)
from .draft_export import (
    DraftExportRecord,
    list_draft_exports,
    record_draft_export,
)
from .extractor import (
    EXTRACTOR_VERSION,
    ExtractedItem,
    ExtractionResult,
    ExtractorError,
    LlmCallable,
    LlmCallResult,
    StoredItem,
    extract_paste,
    list_insights,
    list_open_questions,
    render_prompt,
)
from .gap import (
    CASCADE_VERSION,
    CLUSTER_VERSION,
    GapCluster,
    GapFinderError,
    GapPrompt,
    GapRunResult,
    StoredCluster,
    StoredPrompt,
    StoredRun,
    find_gaps,
    list_gap_runs,
    read_gap_run,
    record_prompt_answer,
    record_prompt_signal,
    would_run_percentage,
)
from .ingest import (
    MAX_PASTE_BYTES,
    PASTE_DOCUMENT_TYPE,
    IngestResult,
    PasteEmptyError,
    PasteTooLargeError,
    ingest_paste,
)
from .paste_log import (
    list_paste_events,
    log_paste_event,
)
from .schema import (
    ANTIEK_RESEARCH_BRIDGE_SCHEMA_V1_SQL,
    init_research_bridge,
    init_research_bridge_at_path,
)
from .source_detection import (
    KNOWN_SOURCES,
    SourceDetectionResult,
    detect_source,
)

__all__ = [
    "ANTIEK_RESEARCH_BRIDGE_SCHEMA_V1_SQL",
    "default_db_path",
    "ensure_research_bridge_initialized",
    "DogfoodMetrics",
    "DogfoodLogValidation",
    "Wave4Candidate",
    "Wave4CandidatesValidation",
    "SessionBlockMetrics",
    "SessionDraftExportMetrics",
    "SessionSignalMetrics",
    "build_dogfood_metrics",
    "DogfoodScaffoldResult",
    "default_dogfood_dir",
    "default_dogfood_metrics_path",
    "render_dogfood_report",
    "DogfoodVerdictScaffoldResult",
    "DogfoodVerdictValidation",
    "default_verdict_path",
    "validate_verdict_doc",
    "write_verdict_scaffold",
    "validate_dogfood_log",
    "validate_wave4_candidates",
    "write_dogfood_scaffold",
    "DraftExportRecord",
    "list_draft_exports",
    "record_draft_export",
    "init_research_bridge",
    "init_research_bridge_at_path",
    "KNOWN_SOURCES",
    "SourceDetectionResult",
    "detect_source",
    "IngestResult",
    "PASTE_DOCUMENT_TYPE",
    "PasteEmptyError",
    "PasteTooLargeError",
    "ingest_paste",
    "MAX_PASTE_BYTES",
    "list_paste_events",
    "log_paste_event",
    "EXTRACTOR_VERSION",
    "ExtractedItem",
    "ExtractionResult",
    "ExtractorError",
    "LlmCallResult",
    "LlmCallable",
    "StoredItem",
    "extract_paste",
    "list_insights",
    "list_open_questions",
    "render_prompt",
    "CASCADE_VERSION",
    "CLUSTER_VERSION",
    "GapCluster",
    "GapFinderError",
    "GapPrompt",
    "GapRunResult",
    "StoredCluster",
    "StoredPrompt",
    "StoredRun",
    "find_gaps",
    "list_gap_runs",
    "read_gap_run",
    "record_prompt_answer",
    "record_prompt_signal",
    "would_run_percentage",
]
